language: node_js

cache:
  - node_modules
  - client/node_modules
  - server/node_modules

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - nvm install $NODE

install:
  - npm i && cd server && npm i && cd ../client && npm i

before_script: 
  - npm i -g typescript
script:
  - npm run build

env:
  - NODE=stable TYPESCRIPT=typescript@latest

node_js:
  - stable

deploy:
  provider: heroku
  api_key:
    secure: ZsyQfVOIjNvXAxr6HpeKZFfsRYFRBs3YywdxVh1Vqh+4DTMEmfA/vZhTwMffnom+cWhET8ntwVcSYgvxv2AriA+Ec5tyGB+bKl+dSQu477w/5/aHbzSPWM1tFG3+w7tO+iMeEX0V+0ow9jIhlvO7l+bNS8I0C5XSphfZOePy+dVreddOAA3G6bQBm5E8FdPjz2eBbRaz7ic4zaS0MasWW6a9OcDSZC/53qlrFu65BuvMw+t04Ej9DyuKPmAMyU4Uq3I5Ot1NuIwsSOKjFduAx5IPLdP36PyRA1IuCdnd2Cn+pf3v4k486HX9KgyIbgYliQ6HJTSesUIQDaQw3G/dagJLa7/PfJueoQSuAs7VVrgqfOdCikvtqGtEggCTPVlQ8D/Af1uxKITx9Jzs2LSx1wrWEqlTK4mZjZbM7+IwFn53DlbXLU7W8t+tYROL+pW/zvUSwXQynYpq7O6XrYh9pFUzGrXmunsVc6SK3UUPloSUPNF+QyiGfWNnJfGYiwHI6YcSGbiyKTORH5ot8suVfAp4GB/weTU5RkL7mFb3cVnyvifEAs0//3svR1d++0XEWhP8mzW7rt1G55ZUhBF8QpWd5+yG7oy6y33qKn48GCypvECYqDRw5qjE6e3axuz9OIzVgEIrQVx4iwze6+4F4OU2PI6NlclwsZPbqrzztYc=
  app: sf-log-analyzer
  skip_cleanup: true
  on:
    branch: dev
