language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - nvm install $NODE

install:
  - npm i && cd server && npm i && cd ../client && npm i

before_script:
  npm i -g typescript

script:
  - npm run build

env:
  - NODE=stable TYPESCRIPT=typescript@latest

node_js:
  - stable

deploy:
  provider: heroku
  api_key:
    secure: lW34ojC+OxQ148VZKJWkI8UsGv708Dnosj3GiGwmGRdA8R1LAJlehRpF/7yhk+VDT2QjftZy3iwg2fnCWh0D4+kqq5oHNxX2JF/EAoIUBpP+K2vp+6Ks3tdlc0F+vV4Xt7lwcUUeL0Y0Ua7R5cTthnc0olz8FmIXMTetq7bMWlf4FOzcUpizJOYz1Lhnh3qqkuCxmUUEwY7L47eQmQUZ+kw8xbTTPuizoEF4qptp2Axyhnet84LQAOVp5ThhomkzaX+Xddqrw1ezZa9zkkx9Y1zv44zOIoiVZwLpJIxiplEw+cd8x4JBHSa4kLrCgeEk/WAd/I7irHMNd97F4wyfbDh+zh+ycFb1UChuLho2mqQgb5nEfDUmxKaCf9hkGgcACoRYkgxdQaK+dhWrojnOBxkq28VVXwkcU/HKpfQfBqe4ftGmIkTCe6JuXaVRxu5bB8NShCUb+KUeu48EzSTpGFkGCOXM3sQZnPCxEzhjJeglbziDMEyAGQzU6kvuvPQhA3OPws05l3GRx0P6CKsfwkBSsuatIhOmJa0YpahDWbq/k5qTbc2MxcGEa1BOPg0PvbV6Y8giYel9YZ1+CvAY9oQoXWEQq+vBFZOPTClsp4NQaNv4iG2nsWLXPuLHdUBdKhjFAIyWbA7RUI8ezzn27BhYrzqmDpFX7/3fbx71nv8=
    app: 
      dev: sf-log-analyzer-dev
      master: sf-log-analyzer-prod