language: node_js

cache:
  - node_modules
  - client/node_modules
  - server/node_modules

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - nvm install $NODE

install:
  - npm i && cd server && npm i && cd ../client && npm i

before_script:
  - npm i -g typescript

script:
  - npm run build

env:
  - NODE=stable TYPESCRIPT=typescript@latest

node_js:
  - stable

deploy:
  provider: heroku
  api_key: c9654d7f-66ae-4239-a306-67aa894b8fec
  app: sf-log-analyzer
  on:
    branch: dev
